version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hccg-postgres
    environment:
      POSTGRES_USER: hccg
      POSTGRES_PASSWORD: hccg2025
      POSTGRES_DB: hccg_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hccg"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: hccg-postgres-test
    environment:
      POSTGRES_USER: hccg
      POSTGRES_PASSWORD: hccg2025
      POSTGRES_DB: hccg_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hccg"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hccg-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: