name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Complete CI/CD Pipeline"]
    types:
      - completed
    branches: [develop, 'p1-*']

jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts from CI
        uses: actions/github-script@v7
        with:
          script: |
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });

            for (const artifact of allArtifacts.data.artifacts) {
              if (artifact.name.startsWith('build-')) {
                const download = await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
                });

                const fs = require('fs');
                fs.writeFileSync(`${artifact.name}.zip`, Buffer.from(download.data));
              }
            }

      - name: Extract artifacts
        run: |
          for zip in build-*.zip; do
            if [ -f "$zip" ]; then
              unzip -q "$zip" -d staging-deploy/
            fi
          done

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment..."

          # Example deployment commands
          # kubectl config use-context staging
          # kubectl apply -f k8s/staging/

          echo "✅ Staging deployment completed"

      - name: Run staging tests
        run: |
          echo "🧪 Running staging validation tests..."
          # Add staging validation tests
          echo "✅ Staging tests passed"

      - name: Notify deployment status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
              state: 'success',
              target_url: 'https://staging.hsinchu-guardian.gov.tw',
              description: 'Deployed to staging successfully',
              context: 'deploy/staging'
            });